# Generated by Django 2.1.7 on 2019-04-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190404_0438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
    ]
